name: "Create release"

on:
  push:
    branches: [ main ]

jobs:
  build-firmware-esp32:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v2
      - name: "Copy static files"
        run: |
          mkdir -p archive/build
          cp Firmware/ESP32/flash_esp32.sh archive/
      - name: "Build ESP32 firmware"
        uses: ./.github/actions/build-esp-idf
        with:
          src-dir: Firmware/ESP32
          out-dir: archive/build
          app-name: openhaystack
      - name: "Create archive"
        uses: actions/upload-artifact@v2
        with:
          name: firmware-esp32
          path: archive/*
          retention-days: 1

  build-and-release:
    name: "Create release on GitHub"
    runs-on: macos-latest
    env:
      APP: OpenHaystack
      PROJECT_DIR: OpenHaystack
    defaults:
      run:
        working-directory: ${{ env.PROJECT_DIR }}
    needs:
      - build-firmware-esp32
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: "Select Xcode 12"
        uses: devbotsxyz/xcode-select@v1
        with:
          version: "latest"
      - name: "Add ESP32 firmware"
        uses: actions/download-artifact@v2
        with:
          name: firmware-esp32
          path: "${{ env.PROJECT_DIR }}/OpenHaystack/HaystackApp/Firmwares/ESP32"
      - name: "Archive project"
        run: xcodebuild archive -scheme ${APP} -configuration release -archivePath ${APP}.xcarchive
      - name: "Create ZIP"
        run: |
          pushd ${APP}.xcarchive/Products/Applications
          zip -r ../../../${APP}.zip ${APP}.app
          popd
      - name: "Create archive"
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.APP }}.zip
          path: ${{ env.PROJECT_DIR }}/${{ env.APP }}.zip
          retention-days: 1
